name: PaperCustomResourceToolkit
version: '0.0.1'
main: daylightnebula.papercustomresourcetoolkit.PaperCustomResourceToolkit
api-version: 1.19
authors: [ DaylightNebula ]
description: A simple toolkit for creating custom entities, blocks, and items.
depends: [ ModelEngine ]
commands:
  getcustomitem:
    description: Get custom item
    usage: /getcustomitem <name or id> [amount]
  createanimatedmodel:
    description: yes
    usage: /createanimatedmodel <model id>
  removeanimatedmodels:
    description: yes
    usage: /removeanimatedmodels
  spawnmob:
    description: Spawn Custom Mob
    usage: /spawnmob <mob id>
  removenearbymobs:
    description: Remove nearby custom mobs of a certain type or of all types
    usage: /removenearbymobs <mob id> <range>
  testui:
    description: yes
    usage: /testui