name: PaperCustomResourceToolkit
version: '${version}'
main: daylightnebula.papercustomresourcetoolkit.PaperCustomResourceToolkit
api-version: 1.19
authors: [ DaylightNebula ]
description: A simple toolkit for creating custom entities, blocks, and items.
